// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: internal/table/proto/table_metadata.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataTypesFormat int32

const (
	DataTypesFormat_UnknownDataTypes DataTypesFormat = 0
	DataTypesFormat_Int              DataTypesFormat = 1
	DataTypesFormat_String           DataTypesFormat = 2
	DataTypesFormat_Bool             DataTypesFormat = 3
)

// Enum value maps for DataTypesFormat.
var (
	DataTypesFormat_name = map[int32]string{
		0: "UnknownDataTypes",
		1: "Int",
		2: "String",
		3: "Bool",
	}
	DataTypesFormat_value = map[string]int32{
		"UnknownDataTypes": 0,
		"Int":              1,
		"String":           2,
		"Bool":             3,
	}
)

func (x DataTypesFormat) Enum() *DataTypesFormat {
	p := new(DataTypesFormat)
	*p = x
	return p
}

func (x DataTypesFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataTypesFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_table_proto_table_metadata_proto_enumTypes[0].Descriptor()
}

func (DataTypesFormat) Type() protoreflect.EnumType {
	return &file_internal_table_proto_table_metadata_proto_enumTypes[0]
}

func (x DataTypesFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataTypesFormat.Descriptor instead.
func (DataTypesFormat) EnumDescriptor() ([]byte, []int) {
	return file_internal_table_proto_table_metadata_proto_rawDescGZIP(), []int{0}
}

type TableFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []*ColumnFormat        `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	RowsCount     uint64                 `protobuf:"varint,5,opt,name=rows_count,json=rowsCount,proto3" json:"rows_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableFormat) Reset() {
	*x = TableFormat{}
	mi := &file_internal_table_proto_table_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableFormat) ProtoMessage() {}

func (x *TableFormat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_table_proto_table_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableFormat.ProtoReflect.Descriptor instead.
func (*TableFormat) Descriptor() ([]byte, []int) {
	return file_internal_table_proto_table_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *TableFormat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TableFormat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableFormat) GetColumns() []*ColumnFormat {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *TableFormat) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TableFormat) GetRowsCount() uint64 {
	if x != nil {
		return x.RowsCount
	}
	return 0
}

type ColumnFormat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType        DataTypesFormat        `protobuf:"varint,2,opt,name=data_type,json=dataType,proto3,enum=internal.DataTypesFormat" json:"data_type,omitempty"`
	IsNullable      bool                   `protobuf:"varint,3,opt,name=is_nullable,json=isNullable,proto3" json:"is_nullable,omitempty"`
	IsPrimaryKey    bool                   `protobuf:"varint,4,opt,name=is_primary_key,json=isPrimaryKey,proto3" json:"is_primary_key,omitempty"`
	IsUnique        bool                   `protobuf:"varint,5,opt,name=is_unique,json=isUnique,proto3" json:"is_unique,omitempty"`
	IsAutoIncrement bool                   `protobuf:"varint,6,opt,name=is_auto_increment,json=isAutoIncrement,proto3" json:"is_auto_increment,omitempty"`
	DefaultValue    string                 `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ColumnFormat) Reset() {
	*x = ColumnFormat{}
	mi := &file_internal_table_proto_table_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnFormat) ProtoMessage() {}

func (x *ColumnFormat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_table_proto_table_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnFormat.ProtoReflect.Descriptor instead.
func (*ColumnFormat) Descriptor() ([]byte, []int) {
	return file_internal_table_proto_table_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *ColumnFormat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnFormat) GetDataType() DataTypesFormat {
	if x != nil {
		return x.DataType
	}
	return DataTypesFormat_UnknownDataTypes
}

func (x *ColumnFormat) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *ColumnFormat) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

func (x *ColumnFormat) GetIsUnique() bool {
	if x != nil {
		return x.IsUnique
	}
	return false
}

func (x *ColumnFormat) GetIsAutoIncrement() bool {
	if x != nil {
		return x.IsAutoIncrement
	}
	return false
}

func (x *ColumnFormat) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

var File_internal_table_proto_table_metadata_proto protoreflect.FileDescriptor

var file_internal_table_proto_table_metadata_proto_rawDesc = string([]byte{
	0x0a, 0x29, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x77, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x6f, 0x77, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x8f, 0x02, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x73, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x73, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x69, 0x73, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x24, 0x0a,
	0x0e, 0x69, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79,
	0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x69, 0x6e, 0x63, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x41,
	0x75, 0x74, 0x6f, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x2a, 0x46, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x73, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x73, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x6e,
	0x74, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12,
	0x08, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x10, 0x03, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x67, 0x68, 0x61, 0x76, 0x79, 0x75,
	0x76, 0x61, 0x2f, 0x74, 0x75, 0x72, 0x62, 0x6f, 0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_internal_table_proto_table_metadata_proto_rawDescOnce sync.Once
	file_internal_table_proto_table_metadata_proto_rawDescData []byte
)

func file_internal_table_proto_table_metadata_proto_rawDescGZIP() []byte {
	file_internal_table_proto_table_metadata_proto_rawDescOnce.Do(func() {
		file_internal_table_proto_table_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_table_proto_table_metadata_proto_rawDesc), len(file_internal_table_proto_table_metadata_proto_rawDesc)))
	})
	return file_internal_table_proto_table_metadata_proto_rawDescData
}

var file_internal_table_proto_table_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_table_proto_table_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_table_proto_table_metadata_proto_goTypes = []any{
	(DataTypesFormat)(0), // 0: internal.DataTypesFormat
	(*TableFormat)(nil),  // 1: internal.TableFormat
	(*ColumnFormat)(nil), // 2: internal.ColumnFormat
}
var file_internal_table_proto_table_metadata_proto_depIdxs = []int32{
	2, // 0: internal.TableFormat.columns:type_name -> internal.ColumnFormat
	0, // 1: internal.ColumnFormat.data_type:type_name -> internal.DataTypesFormat
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_table_proto_table_metadata_proto_init() }
func file_internal_table_proto_table_metadata_proto_init() {
	if File_internal_table_proto_table_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_table_proto_table_metadata_proto_rawDesc), len(file_internal_table_proto_table_metadata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_table_proto_table_metadata_proto_goTypes,
		DependencyIndexes: file_internal_table_proto_table_metadata_proto_depIdxs,
		EnumInfos:         file_internal_table_proto_table_metadata_proto_enumTypes,
		MessageInfos:      file_internal_table_proto_table_metadata_proto_msgTypes,
	}.Build()
	File_internal_table_proto_table_metadata_proto = out.File
	file_internal_table_proto_table_metadata_proto_goTypes = nil
	file_internal_table_proto_table_metadata_proto_depIdxs = nil
}
